{
 "title": "Dashboard - Fabian Santibañez",
 "time": { "from": "now-8d", "to": "now" },
 "panels": [
  {
   "title": "Uso de Red - Fabian S.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{instance=\"localhost:8080\"}[5m])\t",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de CPU - Instancia - Fabian S.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"localhost:8080\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memoria - Fabian S.",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}